apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
  labels:
    tier: kuard
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: kuard
  template:
    metadata:
      labels:
        app: kuard
        version: "2"
        tier: kuard
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:green"